language: rust
cache: cargo
sudo: false
git:
  depth: 10

script: script/cibuild
rust:
  - beta
  - stable
env:
  - SPEC=false
  - SPEC=true
matrix:
  fast_finish: true
  allow_failures:
    - rust: beta
